[package]
name = "habitat_sup"
version = "0.0.0"
authors = ["Adam Jacob <adam@chef.io>", "Jamie Winsor <reset@chef.io>", "Fletcher Nichol <fnichol@chef.io>", "Joshua Timberman <joshua@chef.io>", "Dave Parfitt <dparfitt@chef.io>"]
build = "../build.rs"
workspace = "../../"

[lib]
name = "habitat_sup"

[[bin]]
name = "hab-sup"
doc = false

[[test]]
name = "functional"

[dependencies]
ansi_term = "*"
env_logger = "*"
handlebars = "*"
hyper = "*"
lazy_static = "*"
libc = "*"
log = "*"
iron = "*"
openssl = "0.7" # lock until hyper bumps to 0.8+
persistent = "*"
rand = "*"
regex = "*"
rustc-serialize = "*"
router = "*"
temp_utp = "*"
tempdir = "*"
threadpool = "*"
time = "*"
toml = "*"
url = "*"
wonder = "*"

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_common]
path = "../common"

[dependencies.habitat_depot_client]
path = "../builder-depot-client"

[dependencies.habitat_butterfly]
path = "../butterfly"

[dependencies.uuid]
version = "*"
features = ["rustc-serialize", "v4"]

[dependencies.clap]
version = "*"
features = ["suggestions", "color"]

[features]
functional = []

[profile.release]
lto = true
